version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - ${PORT}:${PORT}
            - 9229:9229
        env_file:
            - .env
        depends_on:
            - postgres

    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - ${POSTGRES_PORT}:5432

    pgAdmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - ${PGADMIN_PORT}:80

volumes:
    postgres:
    pgadmin:
